apiVersion: apps/v1
kind: Deployment
metadata:
  name: connected-city-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: connected-city
  template:
    metadata:
      labels:
        app: connected-city
    spec:
      containers:
      - name: myapp
        image: shantayya/connected-app:v1
        resources:
          limits:
            memory: "100Mi"
            cpu: "100m"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: connected-city-service
spec:
  selector:
    app: connected-city
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer

